version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
